name: flutter_template
description: Flutter template Application to checkout for new projects.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

# Build version number is automatically increased in regards to commit count
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Add your project dependencies here 👇
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3


  ## Common Dependencies
  # UI
  cached_network_image: 3.0.0
  # Provider
  provider: 4.0.0
  # RxDart
  rxdart: 0.26.0
  # Device Info
  device_info: 2.0.0
  package_info: 2.0.0
  # Dependency Injection
  get_it: 7.0.0
  # Boilerplate generation
  freezed_annotation: 0.14.1
  json_serializable: 4.1.1
  # Logging
  logging_flutter:
    git:
      url: https://github.com/levin-riegner/logging_flutter.git
  # PaperTrail
  flutter_paper_trail:
    git:
      url: git://github.com/levin-riegner/flutter_paper_trail
      ref: master
  # App version tracking
  lr_app_versioning:
    git:
      url: git@github.com:levin-riegner/lr-app-versioning
      ref: release/1.0.0-nullsafety.1
  # Firebase
  firebase_core: 1.1.0
  firebase_analytics: 8.0.2
  firebase_crashlytics: 2.0.2
  # Network
  chopper: 4.0.0-nullsafety.1
  # Database
  hive: 2.0.4
  hive_flutter: 1.0.0
  # Secure storage
  flutter_secure_storage: 4.2.0
  # Translations
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  # Detect shake to open console
  shake: 1.0.0
  # Theming
  lr_design_system:
    git:
      url: git@github.com:levin-riegner/flutter-design-system
      ref: release/0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Other build dependencies
  build_runner: 2.0.2
  freezed: 0.14.1+3
  # https://github.com/lejard-h/chopper/issues/250
  # chopper_generator: 4.0.0-nullsafety.1
  hive_generator: 1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    - assets/mocks/

  # TODO: Replace with your project's fonts
  # Fonts
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/work_sans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600

  # Adds code generation (synthetic package) support
  generate: true